# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freeport < Formula
  desc "Get a free open TCP port that is ready to use."
  homepage ""
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ansidev/freeport/releases/download/v1.0.4/freeport_1.0.4_darwin_amd64.tar.gz"
      sha256 "3ea467e64adc3b890aadc97298a08f5ac3518211c5e71d04370700fef3cb0b74"

      def install
        bin.install "freeport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ansidev/freeport/releases/download/v1.0.4/freeport_1.0.4_darwin_arm64.tar.gz"
      sha256 "b6c5a563340e5cc0ea05c3bad0b8ae64799861ecaa3fd3082786f9ad0f1c0c41"

      def install
        bin.install "freeport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ansidev/freeport/releases/download/v1.0.4/freeport_1.0.4_linux_amd64.tar.gz"
      sha256 "435de0ef967240c8809a4fc59027b8b6e6fef9c5af117ea026583e3be3095ab9"

      def install
        bin.install "freeport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ansidev/freeport/releases/download/v1.0.4/freeport_1.0.4_linux_arm64.tar.gz"
      sha256 "c3921e887b9db673dd8df93709567112e30322227cdc1ba65858644e67ad69b2"

      def install
        bin.install "freeport"
      end
    end
  end
end
